TITLE: 'Graphformer-config'
#TITLE: 'repr_table4_h36m_mpii3d_model'
#TITLE: 'repr_table6_3dpw_model'
#TITLE: 'repr_table6_h36m_model'
#TITLE: 'repr_table6_mpii3d_model'
DEBUG: false
DEBUG_FREQ: 5
LOGDIR: ''
DEVICE: 'cuda'
EXP_NAME: 'Graphformer'
OUTPUT_DIR: 'experiments'
NUM_WORKERS: 16
SEED_VALUE: 1
DATASET:
  SEQLEN: 16
LOSS:
  KP_2D_W: 300.0
  KP_3D_W: 300.0
  SHAPE_W: 0.06
  POSE_W: 60.0
  D_MOTION_LOSS_W: 0.0
TRAIN:
  BATCH_SIZE: 32
  NUM_ITERS_PER_EPOCH: 500
  #PRETRAINED: './experiments/29-03-2023_23-12-12_GraphformerBEST/model_best.pth.tar'
  #PRETRAINED: './data/base_data/tcmr_demo_model.pth.tar'
  #PRETRAINED: './data/base_data/vibe_model_w_3dpw.pth.tar'
  PRETRAINED: './experiments/16-03-2023_19-03-19_Graphformerbest/model_best.pth.tar'
  PRETRAINED_REGRESSOR: 'data/base_data/spin_model_checkpoint.pth.tar'
  RESUME: ''
  START_EPOCH: 0
  END_EPOCH: 50
  LR_PATIENCE: 5
  DATA_2D_RATIO: 0.6
  OVERLAP: true
  DATASETS_2D:
    - 'Insta'
    # - 'PoseTrack'
  DATASETS_3D:
    - 'ThreeDPW'
    - 'MPII3D'
    - 'Human36M'
  DATASET_EVAL: 'ThreeDPW'
  GEN_LR: 0.00005
  GEN_WD: 0.0
  MOT_DISCR:
    OPTIM: 'Adam'
    LR: 0.0001
    WD: 0.0001
    MOMENTUM: 0.9
    FEATURE_POOL: 'attention'
    ATT:
      LAYERS: 3
      SIZE: 1024
      DROPOUT: 0.2
MODEL:
  TEMPORAL_TYPE: 'graphformer'

  #repr_table4_3dpw_model.yaml
  # DATASETS_2D:
  #   - 'Insta'
  # DATASETS_3D:
  #   - 'ThreeDPW'
  #   - 'MPII3D'
  #   - 'Human36M'
  # DATASET_EVAL: 'ThreeDPW'

  # repr_table4_h36m_mpii3d_model.yaml
  # DATASETS_2D:
  #   - 'Insta'
  #   - 'PoseTrack'
  # DATASETS_3D:
  #   - 'ThreeDPW'
  #   - 'MPII3D'
  #   - 'Human36M'
  # DATASET_EVAL: 'ThreeDPW'

  # repr_table6_3dpw_model.yaml
  # DATASETS_2D:
  #   - 'Insta'
  #   - 'PoseTrack'
  # DATASETS_3D:
  #   - 'MPII3D'
  #   - 'Human36M'
  # DATASET_EVAL: 'ThreeDPW'

  # repr_table6_h36m_model.yaml
  # DATASETS_2D:
  #   - 'Insta'
  # DATASETS_3D:
  #   - 'MPII3D'
  #   - 'Human36M'
  # DATASET_EVAL: 'Human36M'

  # repr_table6_mpii3d_model.yaml
  # DATASETS_2D:
  #   - 'Insta'
  #   - 'PoseTrack'
  # DATASETS_3D:
  #   - 'MPII3D'
  #   - 'Human36M'
  # DATASET_EVAL: 'ThreeDPW'
  